<h2>Connectez-vous!</h2>


<form action="login.php" method="post">
    <fieldset>
        <legend>Identifiant</legend>
        <ul>
            <li>
                <label for="email">Votre mail: </label>
                <input type="text" name="email" placeholder="votre email">
            </li>
            <li>
                <label for="password">Mot de passe: </label>
                <input type="password" name="psw" placeholder="Mot de passe">
            </li>
            <li>
                <input type="submit" value="connection"/>
            </li>
        </ul>
        <div>
	<a href="forgotPassword.php">Mot de passe oublié ?</a>
</div>

    </fieldset>
</form>