<h2>S'enregistrer</h2>


<form action="register.php"method="POST">
    <fieldset>
        <legend>Création du compte</legend>
            <ul>
                <li>
                    <label for="firstName">Prénom</label>
                    <input type="text" name="firstName" placeholder="Votre prénom">
                </li>
                <li>
                    <label for="lastName">Nom</label>
                    <input type="text" placeholder="nom" name="lastName">
                </li>
                <li>
                    <label for="age">Age</label>
                    <input type="text" placeholder="age" name="age">
                </li>
                <li>
                    <label for="email">Email</label>
                    <input type="text" placeholder="mail" name="email">
                </li>
                <li>
                    <label for="psw">Mot de passe</label>
                    <input type="text" placeholder="password" name="psw">
                </li>
                <li>
                <button class="button button-primary" type="submit">S'enregistrer</button>
                </li>
                </li>
            </ul>
    
    </fieldset>
</form>