<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <header>
        <h1>Test ROOTING</h1>
        <nav>
            <ul>
                <li><a href="<?=$requestUrl?>">Home</a></li>
                <li><a href="<?=$requestUrl?>?page=login">login</a></li>
                <li><a href="<?=$requestUrl?>?page=register">register</a></li>
            </ul>
        </nav>
    </header>

    <main>
        <?php include $page.'View.phtml' ?>
    </main>

    <footer>
        <p>FOOTER Commun</p>
    </footer>
</body>
</html>