<h2><i class="fas fa-home"></i>Accueil</h2>


<ul>
    <?php foreach($posts as $post): ?>
    <li>
        <h3><a href="show_post.php?id=<?= $post['Id']?>"><strong><?= htmlspecialchars($post['Title']) ?></strong></a></h3>
    </li>
    <li>
        <?=  substr(htmlspecialchars($post['Contents']),0,20) ?>[...]
    </li>
    <li>
        Rédigé par :<?= htmlspecialchars($post['FirstName']).' '.htmlspecialchars($post['LastName'])?> le <?= htmlspecialchars($post['CreationDate'])?>
    </li>
    <?php endforeach ?>

    
</ul>