
<h2>Enregistrer vous!</h2>

<form class="generic-form" action ="register.php" method="POST">
    <fieldset>
        <legend>Créer un compte</legend>
            <ul>
                <li>
                    <label for="firstName">Prénom</label>
                    <input type="text" placeholder="prénom" name="firstName">
                </li>
                <li>
                    <label for="lastName">Nom</label>
                    <input type="text" placeholder="nom" name="lastName">
                </li>
                <li>
                    <label for="pseudo">Pseudo</label>
                    <input type="text" placeholder="pseudo" name="pseudo">
                </li>
                <li>
                    <label for="email">Email</label>
                    <input type="text" placeholder="mail" name="email">
                </li>
                <li>
                    <label for="psw">Mot de passe</label>
                    <input type="text" placeholder="password" name="psw">
                </li>
                <li>
                <button class="button button-primary" type="submit">S'enregistrer</button>
                </li>
            </ul>
    </fieldset>
</form>